# Coding & Scoring

[Coding:]{.ul}

-   AC = accurate and complete = contains all elements of the main
    > concept on the checklist with no incorrect information 

-   AI = accurate and incomplete = contains no incorrect information,
    > but leaves out at least one essential element of the main concept
    > on the checklist 

-   IC = inaccurate and complete = contains at least one incorrect piece
    > of essential information (e.g., "knight" for "prince") but
    > includes all essential elements of the main concept on the
    > checklist 

-   II = inaccurate and incomplete = clearly corresponds with a main
    > concept on the checklist but includes at least one incorrect
    > essential element and fails to include at least one essential
    > element 

-   AB = absent = did not produce the main concept

[Scoring\*:]{.ul}

<center>

 Code                         | **Richardson and Dalton, 2016**   | **Kong, 2009**                         
------------------------------|:---------------------------------:|:-------------:
 Accurate & Complete (AC)     | 3 Points                          | 3 Points  
 Accurate & Incomplete (AI)   | 2 Points                          | 2 Point 
 Inaccurate & Complete (IC)   | 2 Points	                        | 1 Point  
 Inaccurate & Incomplete (II) | 1 Point                           | 1 Point                              
 Absent (AB)                  | 0 Points                          | 0 Points 
 
 </center>

*\*To our knowledge, norms for AphasiaBank stimuli are only available
for the Richardson & Dalton 2016 scoring system. If using the Kong, 2009
system, scores cannot be compared to the Richardson & Dalton 2016 norms.
See Kong et al., 2016 for main concepts, checklists, and norms for
additional stimuli.*

Nicholas and Brookshire also developed a series of coding rules to
assist in determining the accuracy and completeness of main concepts.
These coding rules are now supplemented with the published checklists,
which provide common alternatives produced for each main concept, since
there is variability in the syntax and vocabulary that could be used to
produce a main concept. These alternative lists are not comprehensive,
so it is possible that a client may produce an acceptable alternative
that is not in the checklist.

Note to Remember:

-   Main concepts do not have to be given in the transcript in the same order they are shown in the main concept list.

    -   [Cinderella Example]{.ul}

        -   Concept: 18. She knew **she had to be home by midnight**
            > because everything will turn back at midnight.

            -   What if this occurs later in the story (e.g., after #21
                > -- something like "she heard the clock and knew she
                > had to be home by midnight")

                -   *Yes, we would still allow that to count. There
                    > seemed to be a couple of "typical" orderings of
                    > MCs. We went with the most frequent when ordering
                    > our list.*

                -   *More/updated information on sequencing for
                    > Cinderella is available via Greenslade et al.,
                    > 2020 -
                    > <https://doi.org/10.1044/2020_AJSLP-19-00151>*

-   If a main concept is spoken several times, score the final version.

-   Essential elements can be produced across multiple utterances.