---
title: ""
output: html_document
---

### Main Concept Analysis Scoring

Each main concept consists of several essential elements, corresponding to the subject, main verb, object (if appropriate), and any subordinate clauses (Nicholas & Brookshire, 1995). The main concept is assigned one of 5 codes depending on the accuracy (are the essential elements accurate?) and completeness (are essential elements present?) of the production.

### Coding

AC = accurate and complete = contains all elements of the main concept on the checklist with no incorrect information

AI = accurate and incomplete = contains no incorrect information, but leaves out at least one essential element of the main concept on the checklist

IC = inaccurate and complete = contains at least one incorrect piece of essential information (e.g., "knight" for "prince") but includes all essential elements of the main concept on the checklist

II = inaccurate and incomplete = clearly corresponds with a main concept on the checklist but includes at least one incorrect essential element and fails to include at least one essential element AB = absent = did not produce the main concept

### Scoring

| Richardson and Dalton, 2016           | Kong, 2009                          |
|---------------------------------------|-------------------------------------|
| Accurate & Complete (AC): 3 Points    | Accurate & Complete (AC): 3 Points  |
| Accurate & Incomplete (AI): 2 Points  | Accurate & Incomplete (AI): 2 Point |
| Inaccurate & Complete (IC): 2 Points	| Inaccurate (I, IC and II): 1 Point  |
| Inaccurate & Incomplete (II): 1       |                                     |
| Absent (AB): 0 Points                 | Absent (AB): 0 Points               |

To our knowledge, norms for AphasiaBank stimuli are only available for the Richardson & Dalton 2016 scoring system. If using the Kong, 2009 system, scores cannot be compared to the Richardson & Dalton 2016 norms. See Kong et al., 2016 for main concepts, checklists, and norms for additional stimuli.

Nicholas and Brookshire also developed a series of coding rules to assist in determining the accuracy and completeness of main concepts. These coding rules are now supplemented with the published checklists, which provide common alternatives produced for each main concept, since there is variability in the syntax and vocabulary that could be used to produce a main concept. These alternative lists are not comprehensive, so it is possible that a client may produce an acceptable alternative that is not in the checklist.

### References

Albright, E., & Purves, B. (2008). Exploring SentenceShaperTM: Treatment and augmentative possibilities. Aphasiology, 22(7-8), 741-752.

Avent, J., & Austermann, S. (2003). Reciprocal scaffolding: A context for communication treatment in aphasia. Aphasiology, 17(4), 397-404.

Coelho, C. A., McHugh, R. E., & Boyle, M. (2000). Semantic feature analysis as a treatment for aphasic dysnomia: A replication. Aphasiology, 14(2), 133-142.

Cupit, J., Rochon, E., Leonard, C., & Laird, L. (2010). Social validation as a measure of improvement after aphasia treatment: Its usefulness and influencing factors. Aphasiology, 24(11), 1486-1500.

Dalton, S. G. H., & Richardson, J. D. (2019). A large-scale comparison of main concept production between persons with aphasia and persons without brain injury. American journal of speech-language pathology, 28(1S), 293-320. Kong, A. P. H., Whiteside, J., & Bargmann, P. (2016). The Main Concept Analysis: Validation and sensitivity in differentiating discourse produced by unimpaired English speakers from individuals with aphasia and dementia of Alzheimer type. Logopedics Phoniatrics Vocology, 41(3), 129-141.

Nicholas, L. E., & Brookshire, R. H. (1995). Presence, completeness, and accuracy of main concepts in the connected speech of non-brain-damaged adults and adults with aphasia. Journal of Speech, Language, and Hearing Research, 38(1), 145-156.

Richardson, J. D., & Dalton, S. G. (2016). Main concepts for three different discourse tasks in a large non-clinical sample. Aphasiology, 30(1), 45-73.

Richardson, J. D., & Dalton, S. G. H. (2020). Main concepts for two picture description tasks: an addition to Richardson and Dalton, 2016. Aphasiology, 34(1), 119-136.

Ross, K. B., & Wertz, R. T. (1999). Comparison of impairment and disability measures for assessing severity of, and improvement in, aphasia. Aphasiology, 13, 113--124.

Stark, J. A. (2010). Content analysis of the fairy tale Cinderella--A longitudinal single-case study of narrative production: "From rags to riches". Aphasiology, 24(6-8), 709-724.
